AllCops:
  TargetRubyVersion: 2.6

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 145

AsciiComments:
 Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

EmptyMethod:
  Enabled: false
